const katogorier = [
  "Spillekonsol",
  "Ur",
  "Symaskine",
  "Strygejern",
  "Kaffemaskine",
  "Stationær computer",
  "Fladskærm 15-17",
  "Fladskærm 19-20",
  "Fladskærm 22-24",
  "Laptop stor",
  "Laptop mellemstor",
  "Laptop lille",
  "Papirskærer",
  "PC-tilbehør",
  "Printer/scanner",
  "Digital kompaktkamera",
  "DSLR eller videokamera",
  "Håndholdt underholdningsenhed",
  "Hovedtelefoner",
  "Mobiltelefon",
  "Tablet",
  "Fladskærm 26-30",
  "Fladskærm 32-37",
  "Hi-Fi integreret",
  "Hi-Fi adskilte enheder",
  "Musikinstrument",
  "Bærbar radio",
  "Projektor",
  "TV- og gaming-tilbehør",
  "Aircondition/dehumidifier",
  "Dekorativ eller sikkerhedsbelysning",
  "Ventilator",
  "Hår- og skønhedsprodukt",
  "Elkedel",
  "Lampe",
  "Elværktøj",
  "Lille køkkenredskab",
  "Brødrister",
  "Legetøj",
  "Støvsuger",
  "Diverse",
  "Møbler",
  "Cykel",
  "Tøj eller tekstil",
  "Diverse",
  "Håndværktøj",
];

export default katogorier;
